/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PioneersRouteImport } from './routes/pioneers'
import { Route as MusicRouteImport } from './routes/music'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PioneersRoute = PioneersRouteImport.update({
  id: '/pioneers',
  path: '/pioneers',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/mission': typeof MissionRoute
  '/music': typeof MusicRoute
  '/pioneers': typeof PioneersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/mission': typeof MissionRoute
  '/music': typeof MusicRoute
  '/pioneers': typeof PioneersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/mission': typeof MissionRoute
  '/music': typeof MusicRoute
  '/pioneers': typeof PioneersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/mission'
    | '/music'
    | '/pioneers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/mission'
    | '/music'
    | '/pioneers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/mission'
    | '/music'
    | '/pioneers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  MissionRoute: typeof MissionRoute
  MusicRoute: typeof MusicRoute
  PioneersRoute: typeof PioneersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pioneers': {
      id: '/pioneers'
      path: '/pioneers'
      fullPath: '/pioneers'
      preLoaderRoute: typeof PioneersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  MissionRoute: MissionRoute,
  MusicRoute: MusicRoute,
  PioneersRoute: PioneersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
